# Generated by Django 5.0.6 on 2024-09-04 15:28

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HeadArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='Created Time')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated Time')),
                ('title', models.CharField(max_length=50, verbose_name='Title')),
                ('description', models.TextField(blank=True, max_length=500, null=True, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Head Article',
                'verbose_name_plural': 'Head Articles',
            },
        ),
        migrations.CreateModel(
            name='SubHeadArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='Created Time')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated Time')),
                ('title', models.CharField(max_length=50, verbose_name='Title')),
                ('description', models.TextField(blank=True, max_length=500, null=True, verbose_name='Description')),
                ('is_free', models.BooleanField(default=False, verbose_name='Is Free')),
                ('type', models.CharField(choices=[('Test', 'تست'), ('Experiment', 'آزمایش')], max_length=50, verbose_name='Type')),
                ('head_article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articles.headarticle', verbose_name='Head Article')),
            ],
            options={
                'verbose_name': 'Sub Head Article',
                'verbose_name_plural': 'Sub Head Articles',
            },
        ),
        migrations.CreateModel(
            name='MiddleArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='Created Time')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated Time')),
                ('title', models.CharField(max_length=50, verbose_name='Title')),
                ('description', models.TextField(blank=True, max_length=500, null=True, verbose_name='Description')),
                ('sub_head_article', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='articles.subheadarticle', verbose_name='Sub Head Article')),
            ],
            options={
                'verbose_name': 'Middle Article',
                'verbose_name_plural': 'Middle Articles',
            },
        ),
        migrations.CreateModel(
            name='LastArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='Created Time')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated Time')),
                ('title', models.CharField(max_length=50, verbose_name='Title')),
                ('description', models.TextField(max_length=500, verbose_name='Description')),
                ('image', models.ImageField(blank=True, null=True, upload_to='article/<django.db.models.fields.CharField>', verbose_name='Image')),
                ('abbreviation_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Abbreviation')),
                ('score', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Score')),
                ('middle_article', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='articles.middlearticle', verbose_name='Middle Article')),
                ('sub_head_article', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='articles.subheadarticle', verbose_name='Sub Head Article')),
            ],
            options={
                'verbose_name': 'Last Article',
                'verbose_name_plural': 'Last Articles',
            },
        ),
    ]
