# Generated by Django 5.0.6 on 2025-01-24 13:15

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="HeadArticle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "create_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Created Time"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated Time"),
                ),
                ("title", models.CharField(max_length=100, verbose_name="Title")),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        max_length=500,
                        null=True,
                        verbose_name="Description",
                    ),
                ),
            ],
            options={
                "verbose_name": "Head Article",
                "verbose_name_plural": "Head Articles",
            },
        ),
        migrations.CreateModel(
            name="LastArticle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "create_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Created Time"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated Time"),
                ),
                ("title", models.CharField(max_length=100, verbose_name="Title")),
                (
                    "description",
                    models.TextField(max_length=500, verbose_name="Description"),
                ),
                (
                    "abbreviation_name",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="Abbreviation",
                    ),
                ),
                (
                    "score",
                    models.FloatField(
                        blank=True,
                        default=0,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(5),
                        ],
                        verbose_name="Score",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        blank=True,
                        default="<django.db.models.fields.CharField>",
                        max_length=100,
                        null=True,
                        unique=True,
                        verbose_name="Slug",
                    ),
                ),
                ("is_free", models.BooleanField(default=False, verbose_name="Is Free")),
            ],
            options={
                "verbose_name": "Last Article",
                "verbose_name_plural": "Last Articles",
            },
        ),
        migrations.CreateModel(
            name="MiddleArticle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "create_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Created Time"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated Time"),
                ),
                ("title", models.CharField(max_length=100, verbose_name="Title")),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        max_length=500,
                        null=True,
                        verbose_name="Description",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        blank=True,
                        default="<django.db.models.fields.CharField>",
                        max_length=100,
                        null=True,
                        unique=True,
                        verbose_name="Slug",
                    ),
                ),
            ],
            options={
                "verbose_name": "Middle Article",
                "verbose_name_plural": "Middle Articles",
            },
        ),
        migrations.CreateModel(
            name="HeadArticleImages",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "create_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Created Time"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated Time"),
                ),
                (
                    "image",
                    models.ImageField(upload_to="head_article/", verbose_name="image"),
                ),
                (
                    "head_article",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="articles.headarticle",
                        verbose_name="Head Article",
                    ),
                ),
            ],
            options={
                "verbose_name": "Head article Images",
                "verbose_name_plural": "Head article Images",
            },
        ),
        migrations.CreateModel(
            name="ArticleImages",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "create_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Created Time"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated Time"),
                ),
                (
                    "image",
                    models.ImageField(upload_to="article/", verbose_name="image"),
                ),
                (
                    "article",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="articles.lastarticle",
                        verbose_name="Article",
                    ),
                ),
            ],
            options={
                "verbose_name": "Article Images",
                "verbose_name_plural": "Article Images",
            },
        ),
        migrations.CreateModel(
            name="ArticleDescription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "create_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Created Time"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated Time"),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        max_length=2000,
                        null=True,
                        verbose_name="Description",
                    ),
                ),
                (
                    "image",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="articles.articleimages",
                        verbose_name="Image",
                    ),
                ),
                (
                    "article",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="articles.lastarticle",
                        verbose_name="Article",
                    ),
                ),
            ],
            options={
                "verbose_name": "Article Description",
                "verbose_name_plural": "Article Description",
            },
        ),
        migrations.AddField(
            model_name="lastarticle",
            name="middle_article",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="articles.middlearticle",
                verbose_name="Middle Article",
            ),
        ),
        migrations.CreateModel(
            name="SubHeadArticle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "create_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Created Time"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated Time"),
                ),
                ("title", models.CharField(max_length=100, verbose_name="Title")),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        max_length=500,
                        null=True,
                        verbose_name="Description",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[("Test", "تست"), ("Experiment", "آزمایش")],
                        max_length=50,
                        verbose_name="Type",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        blank=True,
                        default="<django.db.models.fields.CharField>",
                        max_length=100,
                        null=True,
                        unique=True,
                        verbose_name="Slug",
                    ),
                ),
                (
                    "head_article",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="articles.headarticle",
                        verbose_name="Head Article",
                    ),
                ),
            ],
            options={
                "verbose_name": "Sub Head Article",
                "verbose_name_plural": "Sub Head Articles",
            },
        ),
        migrations.AddField(
            model_name="middlearticle",
            name="sub_head_article",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="articles.subheadarticle",
                verbose_name="Sub Head Article",
            ),
        ),
        migrations.AddField(
            model_name="lastarticle",
            name="sub_head_article",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="articles.subheadarticle",
                verbose_name="Sub Head Article",
            ),
        ),
    ]
