# Generated by Django 5.0.6 on 2024-12-05 15:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lastarticle',
            name='image',
        ),
        migrations.CreateModel(
            name='ArticleImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='Created Time')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated Time')),
                ('image', models.ImageField(upload_to='article/', verbose_name='image')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articles.lastarticle', verbose_name='Article')),
            ],
            options={
                'verbose_name': 'Article Images',
                'verbose_name_plural': 'Article Images',
            },
        ),
        migrations.CreateModel(
            name='ArticleDescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='Created Time')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated Time')),
                ('description', models.TextField(blank=True, max_length=500, null=True, verbose_name='Description')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articles.lastarticle', verbose_name='Article')),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='articles.articleimages', verbose_name='Image')),
            ],
            options={
                'verbose_name': 'Article Description',
                'verbose_name_plural': 'Article Description',
            },
        ),
    ]
