# Generated by Django 5.0.6 on 2024-12-05 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_remove_lastarticle_image_articleimages_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subheadarticle',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True, verbose_name='Slug'),
        ),
    ]
