# Generated by Django 5.0.6 on 2024-12-05 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_subheadarticle_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subheadarticle',
            name='slug',
            field=models.SlugField(blank=True, default='<django.db.models.fields.CharField>', null=True, unique=True, verbose_name='Slug'),
        ),
    ]
