# Generated by Django 5.0.6 on 2024-12-05 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_lastarticle_slug_middlearticle_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articledescription',
            name='description',
            field=models.TextField(blank=True, max_length=2000, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='headarticle',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='lastarticle',
            name='slug',
            field=models.SlugField(blank=True, default='<django.db.models.fields.CharField>', max_length=100, null=True, unique=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='lastarticle',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='middlearticle',
            name='slug',
            field=models.SlugField(blank=True, default='<django.db.models.fields.CharField>', max_length=100, null=True, unique=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='middlearticle',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='subheadarticle',
            name='slug',
            field=models.SlugField(blank=True, default='<django.db.models.fields.CharField>', max_length=100, null=True, unique=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='subheadarticle',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Title'),
        ),
    ]
