# Generated by Django 5.0.6 on 2024-12-11 16:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0006_alter_articledescription_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lastarticle',
            name='score',
            field=models.FloatField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)], verbose_name='Score'),
        ),
    ]
