# Generated by Django 5.0.6 on 2025-01-23 16:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0008_remove_subheadarticle_is_free_lastarticle_is_free"),
    ]

    operations = [
        migrations.CreateModel(
            name="HeadArticleImages",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "create_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Created Time"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated Time"),
                ),
                (
                    "image",
                    models.ImageField(upload_to="head_article/", verbose_name="image"),
                ),
                (
                    "head_article",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="articles.headarticle",
                        verbose_name="Head Article",
                    ),
                ),
            ],
            options={
                "verbose_name": "Article Images",
                "verbose_name_plural": "Article Images",
            },
        ),
    ]
