# Generated by Django 5.0.6 on 2024-12-11 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='hash_identifier',
            field=models.CharField(blank=True, max_length=72, null=True, verbose_name='Hash identifier'),
        ),
    ]
