# Generated by Django 5.0.6 on 2024-10-30 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_user_verification_code_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='degree',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Degree'),
        ),
    ]
