# Generated by Django 5.0.6 on 2024-12-14 14:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('detail_app', '0003_alter_ticketcategory_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, max_length=500, null=True, verbose_name='Description')),
                ('status', models.BooleanField(default=True, verbose_name='Status')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='detail_app.ticket', verbose_name='Ticket')),
            ],
            options={
                'verbose_name': 'Admin Ticket',
                'verbose_name_plural': 'Admin Ticket',
            },
        ),
    ]
