# Generated by Django 5.0.6 on 2024-12-14 14:31

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminticket',
            name='create_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Created Time'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='adminticket',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated Time'),
        ),
    ]
