# Generated by Django 5.0.6 on 2025-02-21 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("detail_app", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ticket",
            name="parent",
        ),
        migrations.AlterField(
            model_name="ticket",
            name="is_answered",
            field=models.BooleanField(default=False, verbose_name="Is Answer"),
        ),
    ]
