# Generated by Django 5.0.6 on 2024-09-18 15:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_alter_lastarticle_score'),
        ('detail_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favorite',
            name='articles',
        ),
        migrations.AddField(
            model_name='favorite',
            name='articles',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='articles.lastarticle', verbose_name='Articles'),
            preserve_default=False,
        ),
    ]
