# Generated by Django 5.0.6 on 2024-12-14 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('detail_app', '0002_alter_blog_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ticketcategory',
            options={'verbose_name': 'Ticket Category', 'verbose_name_plural': 'Ticket Categories'},
        ),
    ]
