# Generated by Django 5.0.6 on 2024-11-07 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detail_app', '0003_ticket'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='is_appropriate',
            field=models.BooleanField(default=False, verbose_name='Is Appropriate'),
        ),
    ]
