# Generated by Django 5.0.6 on 2024-12-20 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("detail_app", "0003_alter_ticketcategory_options"),
    ]

    operations = [
        migrations.RenameField(
            model_name="ticket",
            old_name="is_appropriate",
            new_name="is_answered",
        ),
    ]
