# Generated by Django 5.0.6 on 2024-11-07 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detail_app', '0004_ticket_is_appropriate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactus',
            name='type',
            field=models.CharField(max_length=40, verbose_name='Type'),
        ),
    ]
